# Generated by Django 4.1.4 on 2022-12-26 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolworks',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='schoolworks',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='schoolworks',
            name='study_quality',
        ),
        migrations.AddField(
            model_name='schoolworks',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolworks',
            name='classify',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolworks',
            name='date',
            field=models.TextField(max_length=50),
        ),
    ]
